# yaml-language-server: $schema=https://platen.io/schemas/config/schema.json
# Update to your own settings for URL/title
baseURL: https://thevanillagame.netlify.app/
title:   TVG

module:
  imports:
    - path: github.com/platenio/platen/modules/platen

params:
  description: The Vanilla Game
